### ISSUE TITLE
Can't reproduce the published results.

### ISSUE THREAD

**Issue by yophis** [FrenchKrab/IS2023-powerset-diarization#1]
I'm having problem trying to reproduce the benchmarked numbers. I believe the problem is caused by the clustering, since miss predictions and false alarm rates are exactly the same as ones in the benchmark, only confusion is different. Despite using the pipeline parameters as stated in this repo, confusion rate is always a lot worse than it should be, roughly two times higher.

For instance,

```
# Pretrained hparams
PIPELINE_PARAMS = {
    'clustering': {
        'method': 'centroid',
        'min_cluster_size': 15,
        'threshold': 0.677263421472069,
    },
    'segmentation': {
        'min_duration_off': 0.0,
    },
}

pretrained_pipeline = SpeakerDiarizationPipeline(PRETRAINED_PATH,
                                                 embedding='speechbrain/spkrec-ecapa-voxceleb',
                                                 clustering='AgglomerativeClustering').to(device)
pretrained_pipeline.instantiate(PIPELINE_PARAMS)

ami_protocol = registry.get_protocol('AMI-SDM.SpeakerDiarization.only_words', preprocessors={'audio': FileFinder()})

# Get predictions
predictions, files = [], []
for file in tqdm(ami_protocol.test()):
    prediction = pretrained_pipeline(file)
    predictions.append(prediction)
    files.append(file)

# Get results
res = {}
res['fa'], res['miss'], res['conf'], res['der'] = get_der(predictions, files)

print(f'Pretrained model on training set of AMI mini:')
print(f"{'Title':10} | {'FA%':>6} | {'MISS%':>6} | {'CONF%':>6} | {'DER%':>6}")
print(f"{'Pretrained':10} | {res['fa']*100:6.3f} | {res['miss']*100:6.3f} | {res['conf']*100:6.3f} | {res['der']*100:6.3f}")
```

\
Yielded
  FA% |  MISS% |  CONF% |   DER%
5.059 |   9.644  |   14.594  |  29.297

**Comment by FrenchKrab** [comment]
Thanks for the issue !
The only difference I can see for now is the missing `embedding_exclude_overlap=True` parameter in the pipeline initialization.

And in case that doesn't do the job, do you get the correct DER values when using the repository's RTTMs ?

**Comment by yophis** [comment]
Oh, thank you very much. I totally missed that one. Now I can achieve the SOTA results haha
