### ISSUE TITLE
Hyperparameters for difference datasets

### ISSUE THREAD

**Issue by xiangzai0115** [FrenchKrab/IS2023-powerset-diarization#3]
Hi,

Thanks for this amazing work and reply on extracting speaker posteriors in time yesterrday.

I feel a little bit confused about the hyperparameters for PIPELINE_PARAMS. You provide one setting in README and another one in example jupyter notebook (I guess it is specific for AMI?). If I would like to try just pretrained powerset model on other benchmark datasets, which one should I use?

Cheers,
Xiang

**Comment by xiangzai0115** [comment]
Aha, I think I should use the one under https://github.com/FrenchKrab/IS2023-powerset-diarization/tree/master/hparams/powerset/pretrained/params.yml

**Comment by FrenchKrab** [comment]
Yes indeed, that's the right `params.yml` if you want to apply the pipeline with the more general pretrained model.

**Comment by xiangzai0115** [comment]
Thanks! will close it now.
