### ISSUE TITLE
Convert Powerset soft outputs to multi-class soft outputs

### ISSUE THREAD

**Issue by xiangzai0115** [FrenchKrab/IS2023-powerset-diarization#5]
Hi, thanks for answering my questions before and that did help a lot!

One more question is if I would like to convert powerset model output to vanilla multi-class output in soft scores, such as probabilities, should I still use self._powerset.to_multilabel function to do this? I saw that it would not give complaint if the input to this function is soft score instead of hard one-hots. Just wondering if there is any issue when the input is exactly outputs = self.model(chunks.to(self.device))

**Comment by FrenchKrab** [comment]
If you're trying to do soft multiclass powerset -> soft multilabel, as long as you use the latest version of pyannote.audio (containing commit : https://github.com/pyannote/pyannote-audio/commit/0b45103cb228a81a9d9d776cca92694cb30ddb41), using the `soft=True` parameter, it should work (your "probabilities" must be in the log space).

**Comment by xiangzai0115** [comment]
Sounds good!
